
CREATE TABLE IF NOT EXISTS artistas (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	numero_contacto VARCHAR(20) NOT NULL,
	documento VARCHAR(50) NOT NULL UNIQUE,
	contrasena VARCHAR(255) NOT NULL
);
